### ISSUE TITLE
Please tell me when I give Mjolnir invalid MXID

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/mjolnir#361] opened 2022-08-21 09:15 UTC
**Is your feature request related to a problem? Please describe.**

Whenever I do something wrong, Mjolnir tells me "There was an error processing your command - see console/log for details" (#162) which feels a bit frustating as I don't hace access to the log and the issue may be something very simple.

**Describe the solution you'd like**

When I give Mjolnir an email address or XMPPID while specifying I am banning/unbanning an user, I would like Mjolnir to tell me that Matrix IDs are e.g. `@poke:example.net` not `poke@example.net` or even `@poke@example.net`.

**Describe alternatives you've considered**

#162 might be a viable alternative, but likely give a confusing error message that may not open so easily as a user error.

**Additional context**

I got three phone screenfuls of silliness and pinged the one running the instance before I realized that I am trying to speak XMPP or email at it 😅

**Comment by turt2live** [comment] 2024-10-01 22:13
Effective duplicate of https://github.com/matrix-org/mjolnir/issues/64

**Closed by turt2live** 2024-10-01 22:13 UTC
