### ISSUE TITLE
If somebody mentions the bot in a protected room, mention everybody within the control room

### ISSUE THREAD

**Issue by bkil** [matrix-org/mjolnir#233] opened 2022-02-22 09:25 UTC
* In our use case, there are multiple "super moderators" who are present in the control room
* Not every super moderator is present in the dozens of protected rooms
* In case of spam waves, users usually mention the local mods and the mjolnir bot as well
* If the local mods are not around, the super moderators might be around and they could mind as well deal with the situation if they only knew

**Comment by bkil** [comment] 2022-02-22 09:32
This could perhaps even go through one level of indirection.
If our mjolnir instance is also subscribed to foreign ban lists and the bot is also present in the report room of those ban lists, the bot could also mention mods within that report room.

In the end, foreign community ban list operators that we cooperate with could help in protecting users in our protected rooms.
This could actually be beneficial to the foreign community as well, because spam and troll waves usually move laterally.
I.e., if they could catch a spammer in our room, the spammer will not harass the users in their room in the first place.

To reduce the burden of accidentally mentioning the super moderators, it might just reply with a confirmation at first, for example `like this post to report abuse to the super admins`

**Comment by bkil** [comment] 2022-02-22 09:36
As a convenience feature, mentioning the bot could also produce a reply that mentions every local mod in the room as a shorthand.
This is a commonly requested feature.

On a different note, mentioning each local mod and, each super mod and each mod within foreign communities should ideally be done in tiers according to pager duty or randomization. I.e., don't ping all 10 mods, just 1 at first, then a second one after 1 minute if nobody reacts, then a third one, etc. This could reduce overall interruptions and notifications for people, reducing mod fatigue.

**Comment by Yoric** [comment] 2022-02-22 10:16
I generally like the idea. There is a strong risk that this will be abused, though, so you'd need either an include-list or an exclude-list, perhaps both, to reduce the risk.

I believe that this could be implemented as a (pseudo-)protection, to make it easy to turn on/off.

**Comment by bkil** [comment] 2022-02-22 10:22
Well, like as in the story about the boy who cried wolf, if a user is calling in the SWAT team without there being a troll, that really just means that _he_ is the troll and is the one who needs to be banned. And in the end, the call for help was then justified.

**Comment by Yoric** [comment] 2022-02-22 11:23
Sure, but given how easy it is to create new accounts, in a public room, it's also easy for a troll to mass-create bots that will all abuse this feature.

**Comment by bkil** [comment] 2022-02-22 11:36
Yes, only a single notification-mention should be propagated for a given room within a given time frame.

And it would also be great to consider read receipts. I.e.., if a moderator has already been following recent events, it is not needed to ping anyone else.

But then again, if we want to deal with spam waves where automatic bot account creation is a possible hazard, protection level already needs to be turned up in response by a mod and/or the room made invite-only. Propagating such knowledge to foreign communities can also be useful (i.e., they can close down their rooms before wave ripples to them).

**Comment by heftig** [comment] 2022-02-23 12:42
This is a duplicate of https://github.com/matrix-org/mjolnir/issues/89.

**Comment by bkil** [comment] 2022-02-23 13:43
Thanks. Well, partially, I've since extended its scope.

**Comment by bkil** [comment] 2022-07-24 11:25
Might be implemented using this:
- https://github.com/matrix-org/matrix-spec-proposals/pull/2938/
> MSC2938: Report content to moderators

**Comment by turt2live** [comment] 2024-10-01 21:39
Duplicate of https://github.com/matrix-org/mjolnir/issues/89

**Closed by turt2live** 2024-10-01 21:39 UTC
Labels: T-Enhancement

**Comment by bkil** [comment] 2024-10-02 17:18
Yes, if you ignore all comments.
