### ISSUE TITLE
Temporary ban cmd to prevent gigantic banlists and to moderate proportionally

### ISSUE THREAD

**Issue by ghost** [matrix-org/mjolnir#318] opened 2022-07-02 23:25 UTC
**Is your feature request related to a problem? Please describe.**
Yes and no. The problem is that we end up with a ban list of several hundreds of people if not thousands when it's not necessary to keep a ban after say a month or whatever duration. And certainly not bans from 2 years ago.

**Describe the solution you'd like**
!tban #room(optional if none = all) 2w id reason  
!tban 2w #foo:bar.com @john:matrix.org trolling

Ban for two weeks

Every day at a configurable time, Mjolnir would check the banlist and unban those who's time is passed.

**Describe alternatives you've considered**
Doing it manually.

**Additional context**
This could also bring a benefit of preventing some people from changing to an alt and coming back if they're banned for only 1d or 2d ... !ban would be for permabans.

**Comment by JokerGermany** [comment] 2022-07-03 13:09
In my opinion this is a good proposal for matrix specs for Room Admins, but i don't see any usecase for mjolnir....

**Comment by JokerGermany** [comment] 2022-07-03 13:29
I see mjolnir as the last resort. if i get a report for trolling as mjolnir admin I shrug. The normal use case should be that mjolnir manage a multitude of different kinds of rooms.
That cases where i ban, are that cases who really really earned their report. I think it would be unfair to revoke this "achievement" ;)

But if someone want to implement it, why not ¯\_(ツ)_/¯

**Comment by JokerGermany** [comment] 2022-07-03 14:23
> In addition, this I think wouldn't require "insane work" to implement in the code. Probably just a couple hours for a good programmer.

If you even know how to implement it, why don't you send in a pr?

**Comment by FSG-Cat** [comment] 2022-07-03 23:37
> In my opinion this is a good proposal for matrix specs (Room Admins), but i don't see any usecase for mjolnir....

This is best suited for Bots as far as i am aware due to the DAG not rly having a concept of time.

**Comment by bkil** [comment] 2022-07-31 19:56
One rational use case in the context of automated spammers is to only keep a ban active in the list until the home server admin has deactivated the given account and possibly reported it to the authorities. This could take days or even weeks in case of certain home servers such as matrix.org. Then it would never come back. However, certain home servers don't really deal with abuse very well, and bans directed at them should not be forgotten. I'm not talking ones that are officially "unmoderated" and hence get ACL'd by many, but those home servers who only deem the worst offenders to be worthy for account deactivation.

**Comment by PC-Admin** [comment] 2023-12-11 01:57
This is a duplicate of another issue made previously: https://github.com/matrix-org/mjolnir/issues/142

**Comment by turt2live** [comment] 2024-10-01 21:44
Duplicate of https://github.com/matrix-org/mjolnir/issues/62

**Closed by turt2live** 2024-10-01 21:44 UTC
