### ISSUE TITLE
Rule Test/Query Command

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/mjolnir#299] opened 2022-05-20 14:19 UTC
#### Is your feature request related to a problem? Please describe.
Sometimes, when seeing users in other chats, i'm curious if the user is reported in any of the watched lists of the mjolnir instance.

#### Describe the solution you'd like
Have a `!mjolnir test` or `!mjolnir query` command, which will take in a server/user, and match them against the current-active policies, and print out the recommended action(s) and final resolved outcome, and the lists/origins from which those policies would come.

**Comment by bkil** [comment] 2022-06-22 22:39
Related:
* https://github.com/matrix-org/mjolnir/issues/67
* https://github.com/matrix-org/mjolnir/issues/228
* https://github.com/matrix-org/mjolnir/issues/231
* https://github.com/matrix-org/mjolnir/issues/263

**Comment by turt2live** [comment] 2024-10-01 21:52
Considering duplicate of https://github.com/matrix-org/mjolnir/issues/67

**Closed by turt2live** 2024-10-01 21:52 UTC
