### ISSUE TITLE
Add reaction emoji for adding to a ban list

### ISSUE THREAD

**Issue by Justinzobel** [matrix-org/mjolnir#494] opened 2023-10-29 06:55 UTC
Currently, our team uses `!mjolnir ban spam @someuser:someserver.net spam` but it would make the job even easier if it was an emoji reaction to ban the user on a list from a reaction.

**Comment by turt2live** [comment] 2024-10-01 22:42
Effective duplicate of https://github.com/matrix-org/mjolnir/issues/160

**Closed by turt2live** 2024-10-01 22:42 UTC
Labels: T-Enhancement
