### ISSUE TITLE
Possibillity to ignore a ban from a subscribed list

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/mjolnir#350] opened 2022-08-15 07:58 UTC
**Is your feature request related to a problem? Please describe.**
Using mjolnir without https://matrix.to/#/#matrix-org-coc-bl:matrix.org is really hard, but i have the feeling that they ban very fast people with mjolnir wich should only be banned in their rooms.
But since matrix.org didn't have a "spam only" list, you only have a decision to take it as it is or deal with much spam yourself.

**Describe the solution you'd like**
A "unban" list which overwrite a ban from an watched list. When someone ist on this List you still get a notification if a watched List banned him (preferably in red color) , but he don't get banned.

**Describe alternatives you've considered**
Only geht Notified ( #269 ) when the other list banned someone and then ban it myself, but in my opinion spam bans should be fast...

**Comment by ShadowJonathan** [comment] 2022-10-17 09:31
This is also related to #283

**Comment by turt2live** [comment] 2024-10-01 22:14
Effective duplicate of https://github.com/matrix-org/mjolnir/issues/18

**Closed by turt2live** 2024-10-01 22:14 UTC
