### ISSUE TITLE
"Notify" on list match

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/mjolnir#269] opened 2022-03-30 14:09 UTC
#### Is your feature request related to a problem? Please describe.
I want to subscribe/follow a moderation list, but I do not fully trust or "vibe" with the moderators behind that list, as they could have a different/more strict CoC than my own community would have.

#### Describe the solution you'd like
Be able to subscribe to a list on a "notify" basis, that if there's a match, that match is presented in the management/moderation room, and a quick action on what to do with it. (Follow/ignore)

#### Additional context
Moderation lists are great, but the way they're used today can be a bother because (from what i understand) people are either actively following and applying moderation from every list, or not.

This is a middle ground, where moderation teams for "neighboring" communities are *alerted* to a moderation decision, and can look into it, or at least become aware of such an action, to pay close attention to the members/servers involved.

**Comment by ShadowJonathan** [comment] 2022-03-30 14:22
Additionally; "Ignore" can be expanded to "ignore for this match" and "ignore for any match", the former will notify if a new Notify match appears in a different list, but the latter will ignore any further Notify match.

**Comment by Gnuxie** [comment] 2022-03-30 16:47
For context; Currently the only way watched lists are audited when changed by another user is with https://github.com/matrix-org/mjolnir/blob/main/src/Mjolnir.ts#L971

For bus factor: The problem goes a lot further than improving auditing, there's an entire domain to explore with regards to propagating bans beyond who you trust to be in the moderation room/adjacent communities. Another glaring thing to be careful about is the distinction between banning because a ban was recommended via a watched list and reaffirming that ban by republishing in your own list. Duplicating a published ban should really be done sparingly, as if you aren't banning someone firsthand, you'll want any unban to be propagated to you.

**Comment by ShadowJonathan** [comment] 2022-03-31 07:08
Sounds like some spec/schema changes need to occur then to signal that it's a manually-approved delegated ban, sourcing from a different list, instead of being from your own list.

**Comment by ShadowJonathan** [comment] 2022-05-03 09:22
Thinking about this while working with mjolnir, i think there's two subcategories here; `match-notify` and `change-notify`.

`match-notify` would notify of the rule's existence in the mod room when it comes into existence and matches existing users, or if a user were to join that then matches one of those rules.

`change-notify` would notify on changes in lists themselves.

Both would probably have quick-action buttons, like :heavy_check_mark: and :x:, which'd allow mods to take quick actions on eying the rule. This'd make the rule probably to be added to a default list, with a reference to the original list/event where the rule originated from.

**Comment by turt2live** [comment] 2024-10-01 21:26
Duplicate of https://github.com/matrix-org/mjolnir/issues/68 and/or https://github.com/matrix-org/mjolnir/issues/18

**Closed by turt2live** 2024-10-01 21:26 UTC
