### ISSUE TITLE
ACL Clean command

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/mjolnir#279] opened 2022-05-02 12:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently, when applying ACLs, users from the corresponding ACL'd rooms are not automatically "cleaned up" (kicked), this is fine for purposes of temporarily dampening attacks against a server.

However, in the long term, users might still linger in a room, and other than a manual kick or a room upgrade, these users would stay around.

**Describe the solution you'd like**
A command that clears (kicks) users from a room, based on if they match an ACL. This can be applied on a protected-rooms level, or a specific room level.

`!mjolnir acl-clean <room>`

**Comment by ShadowJonathan** [comment] 2022-05-03 11:39
https://github.com/matrix-org/mjolnir/issues/273 and https://github.com/matrix-org/mjolnir/issues/161 are related to this, likely a dup, though this issue explains an approach on how to handle #161.

**Comment by turt2live** [comment] 2024-10-01 21:57
Duplicate of https://github.com/matrix-org/mjolnir/issues/161

**Closed by turt2live** 2024-10-01 21:57 UTC
