### ISSUE TITLE
Add option to expire a ban after a specified amount of time

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/mjolnir#142] opened 2021-11-12 19:07 UTC
**Describe the solution you'd like**
It would be nice to be able to ban someone for say a week, or a month, or 6 months but then have them automatically unbanned after that time has passed.

**Describe alternatives you've considered**
It could be a specced Matrix feature but that seems a bit more complicated. Which server or client would unban them after the time has passed?

**Comment by Yoric** [comment] 2021-11-15 14:42
We could store this as extensions of MSC2313.

**Comment by PC-Admin** [comment] 2023-07-07 02:17
+1 for this feature. 

This would be quite handy, a lot of the infractions we see don't warrant a permanent lifetime ban. While giving a user no option for retribution seems not only unfair but it tends to breed animosity.

On Perthchat.org we've created a 'TEMP' ban-list that we record dates into for minor infractions, but the manual effort involved is irritating. To keep our ban lists neat we've just been unbanning everyone at the end of each year. (Which is also not ideal!)

Could be a good idea to implement it at the same time https://github.com/matrix-org/mjolnir/issues/62 is being created, since the underlying mechanism would likely be similar.

**Comment by FSG-Cat** [comment] 2023-12-14 21:01
This could be implemented via implementing MSC3908 support and tbh at that time you can aslo resolve #62 via implementing MSC3907

**Comment by turt2live** [comment] 2024-10-01 20:59
I think this is effectively a duplicate of https://github.com/matrix-org/mjolnir/issues/62

**Closed by turt2live** 2024-10-01 20:59 UTC
