### ISSUE TITLE
!mjolnir version command

### ISSUE THREAD

**Issue by ghost** [matrix-org/mjolnir#469] opened 2023-01-12 19:36 UTC
I think a command to report the version of mjolnir could be very useful, I also believe it should include the version number, maybe the branch and the Git commit hash.

**Comment by turt2live** [comment] 2023-01-12 20:11
What is the intended usecase for such a command?

**Comment by turt2live** [comment] 2024-10-01 22:48
Duplicate of https://github.com/matrix-org/mjolnir/issues/236

**Closed by turt2live** 2024-10-01 22:48 UTC
Labels: T-Enhancement
