### ISSUE TITLE
Option to Shadow Ban users

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/mjolnir#266] opened 2022-03-30 07:27 UTC
**Is your feature request related to a problem? Please describe.**
Deactivating a user should be the last resort. If you want to stop a user and check the situation, deactivate is a little bit to much.
Even if i want to let another one control my decision but need to act now, a shadow ban would be helpful

**Describe the solution you'd like**
`!mjolnir shadow-ban <user IDs>`    
Would be great if you could add several user IDs to the command.
https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#controlling-whether-a-user-is-shadow-banned

**Describe alternatives you've considered**
none

**Comment by heftig** [comment] 2022-04-26 19:20
Note that you can only shadow-ban users belonging to your own homeserver.

**Comment by turt2live** [comment] 2024-10-01 21:28
Duplicate of https://github.com/matrix-org/mjolnir/issues/82

**Closed by turt2live** 2024-10-01 21:28 UTC
