### ISSUE TITLE
Server admin feature: Shadow ban support

### ISSUE THREAD

**Issue by NebulaOnion** [matrix-org/mjolnir#473] opened 2023-01-18 17:48 UTC
For synapse, this endpoint has to be called: `POST /_synapse/admin/v1/users/<user_id>/shadow_ban`

**Comment by MadLittleMods** [comment] 2023-04-15 00:44
Duplicate of https://github.com/matrix-org/mjolnir/issues/266

**Closed** 2023-04-15 06:06 UTC
Labels: T-Enhancement
