### ISSUE TITLE
Offer all block lists for Abuse Report based bans 

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/mjolnir#182] opened 2022-01-13 10:04 UTC
**Is your feature request related to a problem? Please describe.**

When handling abuse reports in Mjölnir, it's possible to ban someone but I don't know which block lists the ban is added to. This can be a problem when communities try to maintain curated block lists (e.g. one for spam, one for CoC infringements, etc)

**Describe the solution you'd like**

When receiving an abuse report through Mjolnir, clicking on the ban button shouldn't trigger a confirmation but should get Mjölnir to post a message asking in which CoC list the user should be added (with one text reaction per list)

**Describe alternatives you've considered**

Unfortunately, this is a Margaret case: there is no alternative™

**Comment by Gnuxie** [comment] 2022-01-19 10:38
Seems to be a duplicate of https://github.com/matrix-org/mjolnir/issues/160

@Yoric do you have any thoughts on how we can solve this? I think an intermediate step like the confirmation that lists the shortcodes as reactions could work. We'd have to figure out what that looks like in Element though as it might truncate longer reactions and also lots of reactions to the same message.

**Comment by Yoric** [comment] 2022-01-19 11:48
We really need to write a MSC (and prototype) for better support for UI. In the meantime, I don't see any better solution than reactions. Probably assign numbers to make the list a bit readable, e.g.:

```
1. Spam
2. CoC
3. NSFW in Family friendly room.
4. ...

[1. Spam][2. CoC][3. NSFW ...][4. ...]

```

**Comment by turt2live** [comment] 2024-10-01 21:20
Duplicate of https://github.com/matrix-org/mjolnir/issues/160

**Closed by turt2live** 2024-10-01 21:20 UTC
