### ISSUE TITLE
Unban lists - followable rooms with ban overrides

### ISSUE THREAD

**Issue by bkil** [matrix-org/mjolnir#390] opened 2022-10-18 14:48 UTC
If I don't agree with certain bans on a foreign list, provide a way through which I can unban that given person on our mjolnir instance.

This should ideally be done through "unban lists" - rooms where overrides are being published that other mjolnir instances can also follow, similar to how "ban lists" are implemented.

Related: #228

**Comment by Gnuxie** [comment] 2022-10-18 15:00
I'm going to put my own thoughts on this problem here. There is a problem in that you don't just want to unban someone. It's that you are disagree in list that ban is coming from in some edge cases. This is why I proposed the reinforcement part of https://github.com/matrix-org/matrix-spec-proposals/pull/3849 (The MSC in general needs a lot of work). The end goal being that policies you are likely to disagree with will require confirmation before your mjolnir blindly applies them.

**Comment by bkil** [comment] 2022-10-18 15:14
Let me share the exact scenario. For day to day use, we would actually desire to follow the matrix-coc list because they add certain local bans an advance (while we sleep) due to having insider information.

Requiring confirmation would actually make following that list completely useless for us, because after some hours, our detectors, reporters and mods will have dealt with the abuse autonomously.

It does happen however (let's say in 1% of the cases) that the matrix-coc admin was heavy handed and banned someone without consideration, without discussing with other mods or they just refuse to appeal the ban later on after mitigating and educating the user. In such cases, it would be an acceptable (if not an ideal) compromise for us if mjolnir banned that user on sight and after we get up, we add that user to our own unban list. Then mjolnir could also do its dance with `unban true` on the user and perhaps reinvite her to the rooms where they have been banned.

**Comment by Gnuxie** [comment] 2022-10-18 15:19
Well the idea is you wouldn't need to manually approve each policy in the list, only ones that conflict with the reinforcements you have made previously.

**Comment by turt2live** [comment] 2024-10-01 22:38
Effective duplicate of https://github.com/matrix-org/mjolnir/issues/18

**Closed by turt2live** 2024-10-01 22:38 UTC
Labels: T-Enhancement

**Comment by bkil** [comment] 2024-10-02 00:03
I don't see the duplication. #18 is a vague description of only banning a person if they are present on at least 2 lists. #390 is about manual overrides. For example, you do agree with the code of conduct enforced by the foreign list and the usual workflow. However, every once in a while, you notice that this foreign list will make a mistake and refuse to own up to it and unban, so it sticks. You will then want to remove the ban, but only this one, not all future ones present on less than 2 lists. #530 could be helpful for this specific scenario.

Similarly, if you run the command outlined in #228 and it shows 6 person would be banned if you were to subscribe to a foreign list due to some disowned mistake way back in time, you would add these 6 people to your own unban list, and _then_ you would want to subscribe to that foreign list.

Finally, while you do agree in general to the code of conduct of a given list, you notice that the moderation workflow isn't as reliable and consequential as you want it to be. So you decide to create a shared unban override list. If other communities agree with your assessment, they will also subscribe to your shared unban list before they subscribe to the given foreign ban list in question to mitigate any such problems in the future. #18 wouldn't help here either.

**Comment by turt2live** [comment] 2024-10-02 17:32
Sorry, I think I meant a combination of #18 and https://github.com/matrix-org/mjolnir/issues/77
