### ISSUE TITLE
Handle Matrix room upgrades

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/mjolnir#262] opened 2022-03-25 08:17 UTC
**Is your feature request related to a problem? Please describe.**
It's a pitty that when a room upgrade happen, mjolnir didn't automatically leave the old and join the new room.

**Describe the solution you'd like**
When a room is upgraded, mjolnir should automatically leave the old and join the new room.
Here is the code how matrix/telegram do it and it works just fine:
https://github.com/mautrix/telegram/commit/165f286bfdd7082f2f21564fa500e929bf474c06

**Describe alternatives you've considered**
At least a note in the control room, that a moderator can do it manual...

**Comment by Mikaela** [comment] 2022-08-01 08:49
I think this is a duplicate of https://github.com/matrix-org/mjolnir/issues/167

**Comment by turt2live** [comment] 2024-10-01 21:30
it is

**Closed by turt2live** 2024-10-01 21:30 UTC
